package ktp.ktx.smart.algo.data.model

import kotlinx.serialization.Serializable

@Serializable
data class User(
    val id: Int? = null, // Nullable for new users (auto-generated by the database)
    val username: String,
    val email: String,
    val passwordHash: String, // Store hashed passwords for security
    val lastLoginDate: Long? = null,
    val createdAt: Long? = null,
    val isBanned: Boolean = false,
)
